namespace Codebase.Gameplay.Enums
{
    public enum CatAnimationType
    {
        none = 0,
        
        action_digging,
        action_drink_down,
        action_drink_up,
        action_drop_l_sit,
        action_drop_r_sit,
        action_eat_dowm,
        action_eat_up,
        action_licking_sit,
        action_pet,
        action_pet_lie,
        action_pet_sit,
        action_shaking,
        action_sharpness_claws,
        
        add_aim_dowm,
        add_aim_front,
        add_aim_up,
        add_angry,
        add_blink,
        add_breathe,
        add_ears_heard,
        add_ears_twitch_l,
        add_ears_twitch_r,
        add_incline,
        add_incline_side,
        
        combat_bite_l,
        combat_bite_r,
        combat_damage_bl,
        combat_damage_br,
        combat_damage_fl,
        combat_damage_fr,
        combat_damage_sl,
        combat_damage_sr,
        combat_death_l,
        combat_death_r,
        combat_paw_l,
        combat_paw_r,
        
        idle_base,
        idle_look,
        idle_look_down,
        idle_loog_site,
        idle_stretching,
        idle_yaw,
        
        jump_fall_high,
        jump_fall_low,
        jump_in_place,
        jump_land_run,
        jump_land_stop,
        jump_run,
        
        move_crouch_f,
        move_crouch_idle,
        move_crouch_l,
        move_crouch_r,
        move_crouch_turn_l,
        move_crouch_turn_r,
        move_run_f,
        move_run_l,
        move_run_r,
        move_swim_enter,
        move_swim_f,
        move_swim_idle,
        move_swim_l,
        move_swim_r,
        move_swim_turn_l,
        move_swim_turn_r,
        move_trot_f,
        move_trot_l,
        move_trot_r,
        move_turn_45_l,
        move_turn_45_r,
        move_turn_90_l,
        move_turn_90_r,
        move_walk_f,
        move_walk_l,
        move_walk_r,
        
        rest_edge_from,
        rest_edge_idle,
        rest_edge_to,
        rest_lie_from,
        rest_lie_idle,
        rest_lie_to,
        rest_sit_from,
        rest_sit_idle,
        rest_sit_to,
        rest_sleep_from,
        rest_sleep_idle,
        rest_sleep_to,
    }
}