using System.Collections.Generic;

namespace InternalAssets.Codebase.Gameplay.Entities.Cats.Enums
{
    public enum CatAnimationType
    {
        none = 0,
        
        action_digging,
        action_coding_begin,
        action_coding_loop,
        action_coding_finish,
        action_drink_down,
        action_drink_up,
        action_drop_l_sit,
        action_drop_r_sit,
        action_eat_dowm,
        action_eat_up,
        action_licking_sit,
        action_pet,
        action_pet_lie,
        action_pet_sit,
        action_shaking,
        action_sharpness_claws,
        add_aim_dowm,
        add_aim_front,
        add_aim_up,
        add_angry,
        add_blink,
        add_breathe,
        add_ears_heard,
        add_ears_twitch_l,
        add_ears_twitch_r,
        add_incline,
        add_incline_side,
        combat_bite_l,
        combat_bite_r,
        combat_damage_bl,
        combat_damage_br,
        combat_damage_fl,
        combat_damage_fr,
        combat_damage_sl,
        combat_damage_sr,
        combat_death_l,
        combat_death_r,
        combat_paw_l,
        combat_paw_r,
        idle_base,
        idle_look,
        idle_look_down,
        idle_look_site,
        idle_stretching,
        idle_yaw,
        jump_fall_high,
        jump_fall_low,
        jump_in_place,
        jump_land_run,
        jump_land_stop,
        jump_run,
        move_crouch_f,
        move_crouch_idle,
        move_crouch_l,
        move_crouch_r,
        move_crouch_turn_l,
        move_crouch_turn_r,
        move_run_f,
        move_run_l,
        move_run_r,
        move_swim_enter,
        move_swim_f,
        move_swim_idle,
        move_swim_l,
        move_swim_r,
        move_swim_turn_l,
        move_swim_turn_r,
        move_trot_f,
        move_trot_l,
        move_trot_r,
        move_turn_45_l,
        move_turn_45_r,
        move_turn_90_l,
        move_turn_90_r,
        move_walk_f,
        move_walk_l,
        move_walk_r,
        rest_edge_from,
        rest_edge_idle,
        rest_edge_to,
        rest_lie_from,
        rest_lie_idle,
        rest_lie_to,
        rest_sit_from,
        rest_sit_idle,
        rest_sit_to,
        rest_sleep_from,
        rest_sleep_idle,
        rest_sleep_to,
        custom_walk_forward,
    }

    public static class CatAnimationDurations
    {
        private static readonly Dictionary<string, float> _animationDurations = new()
        {
            { "action_digging", 2.667f },
            { "action_coding_begin", 0.633f },
            { "action_coding_loop", 1.5f },
            { "action_coding_finish", 0.467f },
            { "action_drink_down", 3.0f },
            { "action_drink_up", 3.0f },
            { "action_drop_l_sit", 2.83f },
            { "action_drop_r_sit", 2.83f },
            { "action_eat_dowm", 3.0f },
            { "action_eat_up", 3.0f },
            { "action_licking_sit", 6.67f },
            { "action_pet", 2.67f },
            { "action_pet_lie", 2.67f },
            { "action_pet_sit", 2.67f },
            { "action_shaking", 2.33f },
            { "action_sharpness_claws", 4.333f },
            { "add_aim_dowm", 2.0f },
            { "add_aim_front", 2.0f },
            { "add_aim_up", 2.0f },
            { "add_angry", 1.0f },
            { "add_blink", 0.33f },
            { "add_breathe", 0.33f },
            { "add_ears_heard", 2.667f },
            { "add_ears_twitch_l", 0.6f },
            { "add_ears_twitch_r", 0.6f },
            { "add_incline", 2.0f },
            { "add_incline_side", 2.0f },
            { "combat_bite_l", 1.3f },
            { "combat_bite_r", 1.3f },
            { "combat_damage_bl", 1.33f },
            { "combat_damage_br", 1.33f },
            { "combat_damage_fl", 1.667f },
            { "combat_damage_fr", 1.667f },
            { "combat_damage_sl", 1.33f },
            { "combat_damage_sr", 1.33f },
            { "combat_death_l", 1.33f },
            { "combat_death_r", 1.33f },
            { "combat_paw_l", 1.33f },
            { "combat_paw_r", 1.33f },
            { "idle_base", 2.667f },
            { "idle_look", 3.333f },
            { "idle_look_down", 6.0f },
            { "idle_look_site", 5.33f },
            { "idle_stretching", 4.33f },
            { "idle_yaw", 2.667f },
            { "jump_fall_high", 1.33f },
            { "jump_fall_low", 1.33f },
            { "jump_in_place", 2.6f },
            { "jump_land_run", 0.33f },
            { "jump_land_stop", 0.83f },
            { "jump_run", 1.667f },
            { "move_crouch_f", 1.0f },
            { "move_crouch_idle", 2.667f },
            { "move_crouch_l", 1.0f },
            { "move_crouch_r", 1.0f },
            { "move_crouch_turn_l", 1.0f },
            { "move_crouch_turn_r", 1.0f },
            { "move_run_f", 0.667f },
            { "move_run_l", 0.667f },
            { "move_run_r", 0.667f },
            { "move_swim_enter", 2.0f },
            { "move_swim_f", 1.067f },
            { "move_swim_idle", 1.667f },
            { "move_swim_l", 1.067f },
            { "move_swim_r", 1.067f },
            { "move_swim_turn_l", 1.067f },
            { "move_swim_turn_r", 1.067f },
            { "move_trot_f", 0.8f },
            { "move_trot_l", 0.8f },
            { "move_trot_r", 0.8f },
            { "move_turn_45_l", 1.0f },
            { "move_turn_45_r", 1.0f },
            { "move_turn_90_l", 1.0f },
            { "move_turn_90_r", 1.0f },
            { "move_walk_f", 1.667f },
            { "move_walk_l", 1.667f },
            { "move_walk_r", 1.667f },
            { "rest_edge_from", 1.167f },
            { "rest_edge_idle", 2.667f },
            { "rest_edge_to", 0.833f },
            { "rest_lie_from", 1.33f },
            { "rest_lie_idle", 2.667f },
            { "rest_lie_to", 1.33f },
            { "rest_sit_from", 1.33f },
            { "rest_sit_idle", 2.667f },
            { "rest_sit_to", 1.33f },
            { "rest_sleep_from", 1.33f },
            { "rest_sleep_idle", 2.667f },
            { "rest_sleep_to", 2.667f },
            { "custom_walk_forward", 0.8f },
        };

        public static float GetDuration(string animationName) => _animationDurations[animationName];
    }
}